version: "3"

services:
  app:
    build: .
    container_name: app
    entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    volumes:
      - .:/var/www
    networks:
      - app-laravel-network
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root

  nginx:
    build: .docker/nginx
    container_name: nginx
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - app-laravel-network
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: laravel-redis
    expose:
      - 6379
    networks:
      - app-laravel-network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-laravel-network

networks:
  app-laravel-network:
    driver: bridge
